PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0

ORCA_BUILD_DATE := $(shell date -u +%Y%m%d)

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(ORCA_BUILDTYPE)),)
    ORCA_BUILDTYPE := UNOFFICIAL
endif

ORCA_VERSION_SUFFIX := $(ORCA_BUILD_DATE)-$(ORCA_BUILDTYPE)-$(ORCA_BUILD)

# Internal version
ORCA_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(ORCA_VERSION_SUFFIX)

# Display version
ORCA_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(ORCA_VERSION_SUFFIX)
